Head:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin 
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LeftArm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
RightArm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LeftHand:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
RightHand:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
Pelvis:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LeftLeg:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
RightLeg:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
LeftFoot:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
RightFoot:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
